[package]
name = "rusteenet"
version = "0.1.0"
authors = ["Valentin Lorentz <progval+git@progval.net>"]
build = "build.rs"

[dependencies]

[build-dependencies]
cbindgen = "*"

[lib]
name = "rusteenet"
crate-type = ["dylib"]
